services:
  postgres_support:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_IDENTITY_DB}
      POSTGRES_USER: ${POSTGRES_IDENTITY_USER}
      POSTGRES_PASSWORD: ${POSTGRES_IDENTITY_PASSWORD}
    ports:
      - "${POSTGRES_IDENTITY_PORT}:5432"